[[architecture-additional-concepts-storage]]
= Persistent Storage
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:
:prewrap!:

toc::[]

== Overview

Managing storage is a distinct problem from managing compute resources.
{product-title} leverages the Kubernetes persistent volume (PV) framework to allow
administrators to provision persistent storage for a cluster. Using persistent
volume claims (PVCs), developers can request PV resources without having
specific knowledge of the underlying storage infrastructure.

PVCs are specific to a
xref:../../architecture/core_concepts/projects_and_users.adoc#projects[project]
and are created and used by developers as a means to use a PV. PV resources on
their own are not scoped to any single project; they can be shared across the
entire {product-title} cluster and claimed from any project. After a PV has been
xref:binding[_bound_] to a PVC, however, that PV cannot then be bound to
additional PVCs. This has the effect of scoping a bound PV to a single
xref:../../architecture/core_concepts/projects_and_users.adoc#namespaces[namespace]
(that of the binding project).

PVs are defined by a `PersistentVolume` API object, which represents a piece
of existing networked storage in the cluster that has been provisioned by an
administrator. It is a resource in the cluster just like a node is a cluster
resource. PVs are volume plug-ins like `Volumes`, but have a lifecycle
independent of any individual
xref:../core_concepts/pods_and_services.adoc#pods[pod] that uses the PV. PV
objects capture the details of the implementation of the storage, be that NFS,
iSCSI, or a cloud-provider-specific storage system.

[IMPORTANT]
====
High-availability of storage in the infrastructure is left to the underlying
storage provider.
====

PVCs are defined by a `PersistentVolumeClaim` API object, which represents a
request for storage by a developer. It is similar to a pod in that pods consume
node resources and PVCs consume PV resources. For example, pods can request
specific levels of resources (e.g., CPU and memory), while PVCs can request
specific xref:pv-capacity[storage capacity] and xref:pv-access-modes[access
modes] (e.g, they can be mounted once read/write or many times read-only).

[[lifecycle-of-a-volume-and-claim]]

== Lifecycle of a Volume and Claim

PVs are resources in the cluster. PVCs are requests for those resources and also
act as claim checks to the resource. The interaction between PVs and PVCs have
the following lifecycle.

[[provisioning]]

=== Provisioning

A cluster administrator creates some number of PVs. They carry the details of
the real storage that is available for use by cluster users. They exist in the
API and are available for consumption.

[[binding]]

=== Binding

A user creates a `PersistentVolumeClaim` with a specific amount of storage
requested and with certain access modes. A control loop in the master watches
for new PVCs, finds a matching PV (if possible), and binds them together. The
user will always get at least what they asked for, but the volume may be in
excess of what was requested. To minimize the excess, {product-title} binds to
the smallest PV that matches all other criteria.

Claims remain unbound indefinitely if a matching volume does not exist. Claims
are bound as matching volumes become available. For example, a cluster
provisioned with many 50Gi volumes would not match a PVC requesting 100Gi. The
PVC can be bound when a 100Gi PV is added to the cluster.

[[using]]

=== Using

Pods use claims as volumes. The cluster inspects the claim to find the bound
volume and mounts that volume for a pod. For those volumes that support multiple
access modes, the user specifies which mode is desired when using their claim as
a volume in a pod.

Once a user has a claim and that claim is bound, the bound PV belongs to the
user for as long as they need it. Users schedule pods and access their claimed
PVs by including a `persistentVolumeClaim` in their pod's volumes block. See
xref:pvc-claims-as-volumes[below] for syntax details.

[[releasing]]

=== Releasing

When a user is done with a volume, they can delete the PVC object from the API
which allows reclamation of the resource. The volume is considered "released"
when the claim is deleted, but it is not yet available for another claim. The
previous claimant's data remains on the volume which must be handled according
to policy.

[[reclaiming]]

=== Reclaiming

The reclaim policy of a `PersistentVolume` tells the cluster what to do with
the volume after it is released. Currently, volumes can either be _retained_ or
_recycled_.

Retention allows for manual reclamation of the resource. For those volume
plug-ins that support it, recycling performs a basic scrub on the volume (e.g.,
`rm -rf /<volume>/*`) and makes it available again for a new claim.

[[persistent-volumes]]

== Persistent Volumes

Each PV contains a `spec` and `status`, which is the specification and
status of the volume.

.Persistent Volume Object Definition
====

[source,yaml]
----
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv0003
  spec:
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /tmp
      server: 172.17.0.2

----
====

[[types-of-persistent-volumes]]

=== Types of Persistent Volumes

{product-title} supports the following `PersistentVolume` plug-ins:

ifdef::openshift-enterprise,openshift-origin[]
- xref:../../install_config/persistent_storage/persistent_storage_nfs.adoc#install-config-persistent-storage-persistent-storage-nfs[NFS]
- xref:../../rest_api/kubernetes_v1.adoc#v1-hostpathvolumesource[HostPath]
- xref:../../install_config/persistent_storage/persistent_storage_glusterfs.adoc#install-config-persistent-storage-persistent-storage-glusterfs[GlusterFS]
- xref:../../install_config/persistent_storage/persistent_storage_ceph_rbd.adoc#install-config-persistent-storage-persistent-storage-ceph-rbd[Ceph
RBD]
- xref:../../install_config/persistent_storage/persistent_storage_cinder.adoc#install-config-persistent-storage-persistent-storage-cinder[OpenStack
Cinder]
- xref:../../install_config/persistent_storage/persistent_storage_aws.adoc#install-config-persistent-storage-persistent-storage-aws[AWS Elastic Block Store (EBS)]
- xref:../../install_config/persistent_storage/persistent_storage_gce.adoc#install-config-persistent-storage-persistent-storage-gce[GCE
Persistent Disk]
- xref:../../install_config/persistent_storage/persistent_storage_iscsi.adoc#install-config-persistent-storage-persistent-storage-iscsi[iSCSI]
- xref:../../install_config/persistent_storage/persistent_storage_fibre_channel.adoc#install-config-persistent-storage-persistent-storage-fibre-channel[Fibre Channel]
endif::[]

ifdef::openshift-dedicated[]
- NFS
- HostPath
- GlusterFS
- Ceph RBD
- OpenStack Cinder
- AWS Elastic Block Store (EBS)
- GCE Persistent Disk
- iSCSI
- Fibre Channel
endif::[]

[[pv-capacity]]

=== Capacity

Generally, a PV will have a specific storage capacity. This is set using the
PV's `capacity` attribute. See the
link:https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/resources.md[Kubernetes
Resource Model] to understand the units expected by `capacity`.

Currently, storage capacity is the only resource that can be set or requested.
Future attributes may include IOPS, throughput, etc.

[[pv-access-modes]]

=== Access Modes

A `PersistentVolume` can be mounted on a host in any way supported by the
resource provider. Providers will have different capabilities and each PV's
access modes are set to the specific modes supported by that particular volume.
For example, NFS can support multiple read/write clients, but a specific NFS PV
might be exported on the server as read-only. Each PV gets its own set of access
modes describing that specific PV's capabilities.

Claims are matched to volumes with similar access modes. The only two matching
criteria are access modes and size. A claim's access modes represent a request.
Therefore, the user may be granted more, but never less. For example, if a claim
requests RWO, but the only volume available was an NFS PV (RWO+ROX+RWX), the
claim would match NFS because it supports RWO.

Direct matches are always attempted first. The volume's modes must match or
contain more modes than you requested. The size must be greater than or equal to
what is expected. If two types of volumes (NFS and iSCSI, for example) both have
the same set of access modes, then either of them will match a claim with those
modes. There is no ordering between types of volumes and no way to choose one
type over another.

All volumes with the same modes are grouped, then sorted by size (smallest to
largest). The binder gets the group with matching modes and iterates over each
(in size order) until one size matches.

The access modes are:

[cols="1,1,3",options="header"]
|===

|Access Mode |CLI Abbreviation |Description

|ReadWriteOnce
|`RWO`
|The volume can be mounted as read-write by a single node.

|ReadOnlyMany
|`ROX`
|The volume can be mounted read-only by many nodes.

|ReadWriteMany
|`RWX`
|The volume can be mounted as read-write by many nodes.

|===

[IMPORTANT]
====
A volume's `AccessModes` are descriptors of the volume's capabilities. They
are not enforced constraints. The storage provider is responsible for runtime
errors resulting from invalid use of the resource.

For example, a GCE Persistent Disk has `AccessModes` *ReadWriteOnce* and
*ReadOnlyMany*. The user must mark their claims as `read-only` if they want to
take advantage of the volume's ability for ROX. Errors in the provider show up
at runtime as mount errors.
====

[[pv-recycling-policy]]

=== Recycling Policy

The current recycling policies are:

[cols="1,2",options="header"]
|===

|Recycling Policy |Description

|Retain
|Manual reclamation

|Recycle
|Basic scrub (e.g, `rm -rf /<volume>/*`)

|===

[NOTE]
====
Currently, only NFS and HostPath support the 'Recycle' recycling policy.
====

[[pv-phase]]

=== Phase

A volumes can be found in one of the following phases:

[cols="1,2",options="header"]
|===

|Phase |Description

|Available
|A free resource that is not yet bound to a claim.

|Bound
|The volume is bound to a claim.

|Released
|The claim has been deleted, but the resource is not yet reclaimed by the
cluster.

|Failed
|The volume has failed its automatic reclamation.

|===

The CLI shows the name of the PVC bound to the PV.

[[persistent-volume-claims]]

== Persistent Volume Claims

Each PVC contains a `spec` and `status`, which is the specification and
status of the claim.

.Persistent Volume Claim Object Definition
====

[source,yaml]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

----
====

[[pvc-access-modes]]
=== Access Modes

Claims use the same conventions as volumes when requesting storage with specific
access modes.

[[pvc-resources]]

=== Resources

Claims, like pods, can request specific quantities of a resource. In this case,
the request is for storage. The same
link:https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/resources.md[resource
model] applies to both volumes and claims.

[[pvc-selector]]
=== Selector

Claims can specify a label selector to further filter the set of volumes. Only the volumes whose labels match the selector can be bound to the claim. The selector can consist of two fields:

- matchLabels - the volume must have a label with this value
- matchExpressions - a list of requirements made by specifying key, list of values, and operator that relates the key and values. Valid operators include In, NotIn, Exists, and DoesNotExist.

All of the requirements, from both `matchLabels` and `matchExpressions` are ANDed together – they must all be satisfied in order to match.

[[pvc-class]]
=== Class

A claim can request a particular class by specifying the name of a
`StorageClass`using the annotation `volume.beta.kubernetes.io/storage-class`.
Only PVs of the requested class, ones with the same annotation as the PVC, can
be bound to the PVC.

PVCs don't necessarily have to request a class. A PVC with its annotation set
equal to `""` is always interpreted to be requesting a PV with no class, so it
can only be bound to PVs with no class (no annotation or one set equal to
`""`). A PVC with no annotation is not quite the same and is treated differently
by the cluster depending on whether the `DefaultStorageClass` admission plugin
is turned on.

- If the admission plugin is turned on, the administrator may specify a
default `StorageClass`. All PVCs that have no annotation can be bound only to
PVs of that default. Specifying a default `StorageClass` is done by setting the
annotation `storageclass.beta.kubernetes.io/is-default-class` equal to "true" in
a `StorageClass` object. If the administrator does not specify a default, the
cluster responds to PVC creation as if the admission plugin were turned off. If
more than one default is specified, the admission plugin forbids the creation of
all PVCs.
- If the admission plugin is turned off, there is no notion of a default
`StorageClass`. All PVCs that have no annotation can be bound only to PVs that
have no class. In this case the PVCs that have no annotation are treated the
same way as PVCs that have their annotation set to `""`.

When a PVC specifies a `selector` in addition to requesting a `StorageClass`,
the requirements are ANDed together: only a PV of the requested class and with
the requested labels may be bound to the PVC.

The `selector` can be used to configure a set of zone(s) in which a dynamically provisioned `PersistentVolume` shall be created, as shown in the below example:

====
[source,yaml]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3.5Gi
  selector:
      matchLabels:
        failure-domain.beta.kubernetes.io/region: us-east2
      matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
            - us-east2-a
            - us-east2-b
        - key: failure-domain.beta.kubernetes.io/zone
          operator: NotIn
          values:
            - us-east2-c
----
====

In the future after beta, the `volume.beta.kubernetes.io/storage-class`
annotation will become an attribute.

[[pvc-claims-as-volumes]]

=== Claims As Volumes

Pods access storage by using the claim as a volume. Claims must exist in the
same namespace as the pod using the claim. The cluster finds the claim in the
pod's namespace and uses it to get the `PersistentVolume` backing the claim.
The volume is then mounted to the host and into the pod:

====

[source,yaml]
----
kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: dockerfile/nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim

----
====
